// app/layout.tsx
import { Metadata } from "next"; // Import if you need metadata
import "./globals.css"; // Include global styles
import { Suspense } from "react";
import Loading from "./loading"; // Adjust this import based on your loading component
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Explicitly define the children prop type
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="antialiased">
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Toaster /> {/* This should be included at the root level */}
        </body>
      </html>
    </StoreProvider>
  );
}
